SEED: 7
DEBUG: False
LOG_FREQ: 100
OUTPUT_BASE_DIR: '/storage/shafner/urban_extraction/networks'
SAVE_CHECKPOINTS: [5, 10]
PRETRAINING_CONFIG: 'base_selfsupervised_downstream'
INFERENCE:
  CHECKPOINT: 10
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  TYPE: 'unet'
  OUT_CHANNELS: 2
  IN_CHANNELS: 10
  LOSS_TYPE: 'SoftDiceSquared'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  TOPOLOGY: [64, 128,]
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: None

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B6', 'B8', 'B8A', 'B11', 'B12']
  AUXILIARY_INPUTS: []
  INCLUDE_UNLABELED: False


DATASETS:
  PATH: '/storage/shafner/urban_extraction/urban_dataset/'
  TRAINING: ['albuquerque', 'charlston', 'columbus', 'dallas', 'denver', 'elpaso',
             'kansascity', 'lasvegas',  'miami', 'minneapolis', 'montreal', 'phoenix',
             'quebec', 'saltlakecity', 'sandiego', 'santafe',  'stgeorge', 'toronto',
             'tucson', 'winnipeg']
  PRETRAINING: ['houston', 'seattle', 'losangeles', 'atlanta',
                'beijing', 'dakar', 'dubai', 'jakarta', 'kairo', 'kigali', 'lagos', 'mexicocity', 'mumbai',
                'riodejanairo', 'shanghai', 'buenosaires', 'bogota', 'sanjose', 'santiagodechile', 'kapstadt', 'tripoli',
                'freetown', 'london', 'madrid', 'kinshasa', 'manila', 'moscow', 'newdehli', 'nursultan', 'perth',
                'tokio', 'stockholm', 'sidney', 'maputo', 'caracas', 'santacruzdelasierra', 'saopaulo', 'asuncion',
                'lima', 'paramaribo', 'libreville', 'djibuti', 'beirut', 'baghdad', 'athens', 'islamabad', 'hanoi',
                'bangkok', 'dhaka', 'bengaluru', 'taipeh', 'berlin', 'nanning', 'wuhan', 'daressalam', 'milano',
                'zhengzhou', 'hefei', 'xian', 'seoul', 'ibadan', 'benincity', 'abidjan', 'accra']
  VALIDATION: ['calgary', 'newyork', 'sanfrancisco', 'vancouver']
  TESTING: '/storage/shafner/urban_extraction/urban_dataset/sn7/'

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 16
  EPOCHS: 10
  OPTIMIZER: 'adamw'

AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  DOWNSCALE: []
  SENSOR_DROPOUT: False
  CHANNEL_DROPOUT: False