SEED: 7
DEBUG: False
LOG_FREQ: 200
OUTPUT_BASE_DIR: '/storage/shafner/urban_extraction/networks'
SAVE_CHECKPOINTS: [1, 2, 5]
INFERENCE:
  CHECKPOINT: 1
  THRESHOLDS:
    TRAIN: 0.0
    VALIDATION: 0.0

MODEL:
  TYPE: 'dualstreamunet'
  OUT_CHANNELS: 1
  IN_CHANNELS: 12
  LOSS_TYPE: 'JaccardLikeLoss'
  POSITIVE_WEIGHT: 250
  NEGATIVE_WEIGHT: 1
  TOPOLOGY: [64, 128,]
  BACKBONE:
    ENABLED: False
    TYPE: 'resnet34'
    PRETRAINED_WEIGHTS: None

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  LABEL: 'buildings'
  LABEL_THRESH: 0.0
  MODE: 'fusion'
  SENTINEL1_BANDS: ['VV', 'VH']
  SENTINEL2_BANDS: ['B2', 'B3', 'B4', 'B5', 'B6', 'B6', 'B8', 'B8A', 'B11', 'B12']
  AUXILIARY_INPUTS: []
  INCLUDE_UNLABELED: True


DATASETS:
  PATH: '/storage/shafner/urban_extraction/urban_dataset/'
  TRAINING: ['albuquerque']
  VALIDATION: ['calgary']
  UNLABELED: ['stockholm']
  TESTING: '/storage/shafner/urban_extraction/urban_dataset/sn7/'

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 5
  OPTIMIZER: 'adamw'

AUGMENTATION:
  IMAGE_OVERSAMPLING_TYPE: 'none' # [none, simple]
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: True
  DOWNSCALE: []
  SENSOR_DROPOUT: False
  CHANNEL_DROPOUT: False

CONSISTENCY_TRAINER:
  LOSS_FACTOR: 0.1
  WEIGHT_DECAY: 0.998
  APPLY_THRESHOLD: False
  CONSISTENCY_LOSS_TYPE: 'JaccardLikeLoss'