_BASE_: "base.yaml"
DEBUG: False
INFERENCE:
  CHECKPOINT: 15
  THRESHOLDS:
    TRAIN: 0.00
    VALIDATION: 0.00

MODEL:
  IN_CHANNELS: 10
  LOSS_TYPE: 'JaccardMoreLikeLoss'

DATALOADER:
  MODE: 'optical'